USE dummyDB;

SELECT * FROM EMPLOYEES;
SELECT * FROM JOBS;

SELECT CONCAT(EMPLOYEES.FIRST_NAME, ' ', EMPLOYEES.LAST_NAME) AS NAME, JOBS.JOB_TITLE AS JOB
FROM EMPLOYEES, JOBS
WHERE EMPLOYEES.JOB_ID = JOBS.JOB_ID;

SELECT CONCAT(EMPLOYEES.FIRST_NAME, ' ', EMPLOYEES.LAST_NAME) AS NAME, JOBS.JOB_TITLE AS JOB
FROM EMPLOYEES JOIN JOBS USING(JOB_ID);

SELECT CONCAT(EMPLOYEES.FIRST_NAME, ' ', EMPLOYEES.LAST_NAME) AS NAME, JOBS.JOB_TITLE AS JOB, EMPLOYEES.SALARY
FROM EMPLOYEES JOIN JOBS USING(JOB_ID)
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

SELECT CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS NAME, CONCAT(M.FIRST_NAME, ' ', M.LAST_NAME) AS MANAGER 
FROM EMPLOYEES AS E
	JOIN EMPLOYEES AS M
		ON E.MANAGER_ID = M.EMPLOYEE_ID;

